import type { ConvertOutputMode } from "@/lib/types";

/**
 * Deterministic, best-practice email template generator. Used as the
 * graceful fallback for CONVERT when no AI provider is configured, and as a
 * reference structure. The output follows every hard requirement: tables,
 * inline CSS, alt/width/height attributes, role="presentation", MSO
 * conditionals, dark-mode meta, 44px CTA, email-safe fonts, no JS/flex/grid.
 */
export function buildStarterEmail(mode: ConvertOutputMode): string {
  if (mode === "mjml") {
    return buildMjml();
  }
  if (mode === "foundation") {
    return buildFoundation();
  }
  return buildStandard(mode === "sfmc");
}

function buildStandard(sfmc: boolean): string {
  const ampscriptOpen = sfmc
    ? "%%[ /* AMPscript: personalization variables */ VAR @firstName SET @firstName = AttributeValue(\"FirstName\") ]%%\n"
    : "";
  const greeting = sfmc ? "Hi %%=v(@firstName)=%%," : "Hi there,";
  const unsub = sfmc
    ? '<a href="%%unsub_center_url%%" style="color:#777777;">Unsubscribe</a>'
    : '<a href="{{unsubscribe_url}}" style="color:#777777;">Unsubscribe</a>';

  return `${ampscriptOpen}<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="en" xmlns="http://www.w3.org/1999/xhtml" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="color-scheme" content="light dark" />
  <meta name="supported-color-schemes" content="light dark" />
  <meta name="format-detection" content="telephone=no" />
  <title>EmailForge Template</title>
  <!--[if mso]>
  <noscript>
    <xml>
      <o:OfficeDocumentSettings>
        <o:PixelsPerInch>96</o:PixelsPerInch>
      </o:OfficeDocumentSettings>
    </xml>
  </noscript>
  <![endif]-->
  <style type="text/css">
    body { margin: 0; padding: 0; width: 100% !important; -webkit-text-size-adjust: 100%; }
    table { border-collapse: collapse; }
    img { border: 0; line-height: 100%; outline: none; text-decoration: none; -ms-interpolation-mode: bicubic; }
    @media only screen and (max-width: 600px) {
      .container { width: 100% !important; }
      .stack { display: block !important; width: 100% !important; }
      .cta-button a { display: block !important; }
    }
    @media (prefers-color-scheme: dark) {
      .bg-body { background-color: #111111 !important; }
      .card { background-color: #1c1c1c !important; }
      .text { color: #f5f5f5 !important; }
    }
  </style>
</head>
<body class="bg-body" style="margin:0; padding:0; background-color:#f4f4f5; font-family: Arial, Helvetica, sans-serif;">
  <div style="display:none; max-height:0; overflow:hidden; font-size:1px; line-height:1px; color:#f4f4f5;">
    Your preview text goes here and previews in the inbox before opening.
  </div>
  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="background-color:#f4f4f5;">
    <tr>
      <td align="center" style="padding:24px 12px;">
        <!--[if mso]><table role="presentation" width="600" cellpadding="0" cellspacing="0" border="0"><tr><td><![endif]-->
        <table role="presentation" class="container card" width="600" cellpadding="0" cellspacing="0" border="0" style="width:600px; max-width:600px; background-color:#ffffff; border-radius:12px;">
          <!-- Header / Logo -->
          <tr>
            <td align="center" style="padding:32px 32px 16px 32px;">
              <img src="https://via.placeholder.com/160x40?text=LOGO" width="160" height="40" alt="Company logo" style="display:block; border:0;" />
            </td>
          </tr>
          <!-- Hero headline (live text, not an image) -->
          <tr>
            <td align="center" class="text" style="padding:8px 32px; font-family: Arial, Helvetica, sans-serif; font-size:28px; line-height:1.3; font-weight:700; color:#111111;">
              A headline built with live HTML text
            </td>
          </tr>
          <!-- Body copy -->
          <tr>
            <td align="left" class="text" style="padding:16px 32px; font-family: Arial, Helvetica, sans-serif; font-size:16px; line-height:1.6; color:#444444;">
              ${greeting}<br /><br />
              This responsive, accessible template was generated by EmailForge. It uses tables, inline CSS and email-safe fonts so it renders consistently across Outlook, Gmail, Yahoo and Apple Mail.
            </td>
          </tr>
          <!-- Bulletproof CTA (>=44px tall) -->
          <tr>
            <td align="center" style="padding:8px 32px 32px 32px;">
              <table role="presentation" cellpadding="0" cellspacing="0" border="0" class="cta-button">
                <tr>
                  <td align="center" bgcolor="#111111" style="border-radius:8px;">
                    <a href="https://example.com" target="_blank" style="display:inline-block; padding:14px 28px; font-family: Arial, Helvetica, sans-serif; font-size:16px; line-height:1; font-weight:700; color:#ffffff; text-decoration:none; border-radius:8px;">
                      Get started
                    </a>
                  </td>
                </tr>
              </table>
            </td>
          </tr>
          <!-- Footer / Legal -->
          <tr>
            <td align="center" style="padding:24px 32px; font-family: Arial, Helvetica, sans-serif; font-size:12px; line-height:1.6; color:#777777;">
              EmailForge Inc., 123 Sender Street, Suite 100, San Francisco, CA 94107<br />
              ${unsub} &nbsp;|&nbsp; <a href="#" style="color:#777777;">View in browser</a>
            </td>
          </tr>
        </table>
        <!--[if mso]></td></tr></table><![endif]-->
      </td>
    </tr>
  </table>
</body>
</html>`;
}

function buildMjml(): string {
  return `<mjml>
  <mj-head>
    <mj-attributes>
      <mj-all font-family="Arial, Helvetica, sans-serif" />
      <mj-text font-size="16px" line-height="1.6" color="#444444" />
    </mj-attributes>
    <mj-style>
      @media (prefers-color-scheme: dark) {
        .card { background-color: #1c1c1c !important; }
      }
    </mj-style>
  </mj-head>
  <mj-body background-color="#f4f4f5">
    <mj-section background-color="#ffffff" border-radius="12px" css-class="card" padding="32px">
      <mj-column>
        <mj-image src="https://via.placeholder.com/160x40?text=LOGO" alt="Company logo" width="160px" />
        <mj-text align="center" font-size="28px" font-weight="700" color="#111111">A headline built with live text</mj-text>
        <mj-text>Hi there, this responsive template was generated by EmailForge and compiles to bulletproof HTML.</mj-text>
        <mj-button background-color="#111111" color="#ffffff" border-radius="8px" inner-padding="14px 28px" href="https://example.com">Get started</mj-button>
      </mj-column>
    </mj-section>
    <mj-section padding="16px">
      <mj-column>
        <mj-text align="center" font-size="12px" color="#777777">
          EmailForge Inc., 123 Sender Street, San Francisco, CA 94107<br />
          <a href="{{unsubscribe_url}}">Unsubscribe</a>
        </mj-text>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>`;
}

function buildFoundation(): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>EmailForge Template</title>
</head>
<body>
  <table class="body" role="presentation" width="100%" cellpadding="0" cellspacing="0">
    <tr>
      <td class="float-center" align="center" valign="top">
        <center>
          <container>
            <row class="header">
              <columns>
                <img src="https://via.placeholder.com/160x40?text=LOGO" alt="Company logo" width="160" height="40" />
              </columns>
            </row>
            <row>
              <columns>
                <h1>A headline built with live text</h1>
                <p>Hi there, this Foundation for Emails (Inky) template was generated by EmailForge.</p>
                <button class="large expanded" href="https://example.com">Get started</button>
              </columns>
            </row>
            <row class="footer">
              <columns>
                <p class="text-center">EmailForge Inc., 123 Sender Street, San Francisco, CA 94107<br />
                <a href="{{unsubscribe_url}}">Unsubscribe</a></p>
              </columns>
            </row>
          </container>
        </center>
      </td>
    </tr>
  </table>
</body>
</html>`;
}
